services:

  streamlit_accesscontrol:
    container_name: streamlit_accesscontrol

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8501:8501"

    volumes:
    - ./src:/app/src  # Map local files to the container for live updates (useful for development)

    environment:
      - PYTHONUNBUFFERED=1  # Avoid output buffering; this line ensures that print() statements are sent directly to the terminal

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3

    restart: unless-stopped

    # Custom command to specify the configuration flags you'd like to pass
    command: ["streamlit", "run", "run_streamlit.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]
    # "--logger.level=debug"




##################### CLOUDFLARED #####################
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel

    # network_mode: service:streamlit_accesscontrol

    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}

    command: tunnel run # tunnel --loglevel debug run

    depends_on:
      - streamlit_accesscontrol  # Ensure Cloudflared waits for Open WebUI to be available before starting

    restart: unless-stopped
